
CREATE TABLE IF NOT EXISTS products (
  product_id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(255) DEFAULT NULL,
  category VARCHAR(255) DEFAULT NULL,
  quantity SMALLINT DEFAULT NULL,
  quantity_sold SMALLINT DEFAULT NULL,
  price REAL DEFAULT NULL,
  sales SMALLINT DEFAULT NULL,
  created_timestamp TIMESTAMP DEFAULT NOW()
);
