
CREATE TABLE IF NOT EXISTS users (
  user_id TEXT NOT NULL PRIMARY KEY,
  username VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  role VARCHAR(255) DEFAULT 'Admin',
  created_timestamp TIMESTAMP DEFAULT NOW()
);
